"""
Extend ligand library with ChEMBL FDA-approved drugs (199 from chembl_fda_approved.csv).
Prepares 3D SDF → PDBQT using existing pipeline functions.
"""
import os, sys, json, csv, time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from rdkit import Chem
from rdkit.Chem import AllChem, Descriptors, rdMolDescriptors
from rdkit.Chem.Descriptors import MolWt, MolLogP

BASE = Path(r"D:\Researching\SMVT")
DATA_DIR = BASE / "03_Analysis" / "data"
LIGANDS_DIR = DATA_DIR / "ligands"
PDBQT_DIR = DATA_DIR / "pdbqt_ligands"
os.makedirs(LIGANDS_DIR, exist_ok=True)
os.makedirs(PDBQT_DIR, exist_ok=True)

# Copy in the helper functions from 01_prepare_ligands.py
def prepare_3d_molecule(name, smiles, properties=None):
    if properties is None:
        properties = {}
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    mol.SetProp("_Name", name)
    for k, v in properties.items():
        mol.SetProp(k, str(v))
    mol = Chem.AddHs(mol)
    params = AllChem.ETKDGv3()
    params.randomSeed = 42
    result = AllChem.EmbedMolecule(mol, params)
    if result == -1:
        params = AllChem.ETKDG()
        params.randomSeed = 42
        result = AllChem.EmbedMolecule(mol, params)
    if result == 0:
        try:
            AllChem.MMFFOptimizeMolecule(mol)
        except:
            pass
    safe_name = name.replace("/", "_").replace(" ", "_").replace(",", "")
    # Also replace special characters
    for ch in "()[]{}'\"*":
        safe_name = safe_name.replace(ch, "_")
    sdf_path = LIGANDS_DIR / f"{safe_name}.sdf"
    writer = Chem.SDWriter(str(sdf_path))
    writer.write(mol)
    writer.close()
    return {
        "name": safe_name,
        "sdf": str(sdf_path),
        "smiles": smiles,
        "mwt": round(MolWt(mol), 2),
        "logp": round(MolLogP(mol), 2),
        "hbd": Descriptors.NumHDonors(mol),
        "hba": Descriptors.NumHAcceptors(mol),
        "rotatable": rdMolDescriptors.CalcNumRotatableBonds(mol),
    }


def convert_to_pdbqt_meeko(record):
    from meeko import MoleculePreparation, PDBQTWriterLegacy
    sdf_path = record["sdf"]
    name = record["name"]
    pdbqt_path = PDBQT_DIR / f"{name}.pdbqt"
    if pdbqt_path.exists() and os.path.getsize(pdbqt_path) > 100:
        record["pdbqt"] = str(pdbqt_path)
        return True
    suppl = Chem.SDMolSupplier(sdf_path, removeHs=False)
    mol = next(iter(suppl), None)
    if mol is None:
        return False
    mol = Chem.AddHs(mol)
    try:
        preparator = MoleculePreparation()
        mol_setups = preparator.prepare(mol)
        if not mol_setups:
            return False
        pdbqt_string, is_ok, err_msg = PDBQTWriterLegacy.write_string(mol_setups[0])
        if not is_ok:
            return False
        with open(pdbqt_path, "w") as f:
            f.write(pdbqt_string)
        record["pdbqt"] = str(pdbqt_path)
        return True
    except:
        return False


def convert_to_pdbqt_obabel(record):
    sdf_path = record["sdf"]
    name = record["name"]
    pdbqt_path = PDBQT_DIR / f"{name}.pdbqt"
    if pdbqt_path.exists() and os.path.getsize(pdbqt_path) > 100:
        record["pdbqt"] = str(pdbqt_path)
        return True
    obabel = r"C:\anaconda3\Scripts\obabel.exe"
    cmd = f'"{obabel}" "{sdf_path}" -O "{pdbqt_path}" 2>nul'
    ret = os.system(cmd)
    if ret == 0 and pdbqt_path.exists() and os.path.getsize(pdbqt_path) > 50:
        record["pdbqt"] = str(pdbqt_path)
        return True
    return False


def convert_to_pdbqt_manual(record):
    """Fallback PDBQT writer."""
    from rdkit import Chem
    sdf_path = record["sdf"]
    name = record["name"]
    pdbqt_path = PDBQT_DIR / f"{name}.pdbqt"
    if pdbqt_path.exists() and os.path.getsize(pdbqt_path) > 100:
        record["pdbqt"] = str(pdbqt_path)
        return True
    suppl = Chem.SDMolSupplier(sdf_path)
    mol = next(iter(suppl), None)
    if mol is None:
        return False
    conf = mol.GetConformer()
    lines = [f"REMARK  GENERATED BY RDKit\n"]
    for i, atom in enumerate(mol.GetAtoms(), 1):
        pos = conf.GetAtomPosition(atom.GetIdx())
        elem = atom.GetSymbol()
        ad4 = elem if elem != 'H' else 'H'
        if elem in ('C', 'N', 'O', 'S', 'F', 'P'):
            ad4 = elem
        elif elem == 'Cl': ad4 = 'Cl'
        elif elem == 'Br': ad4 = 'Br'
        elif elem == 'I': ad4 = 'I'
        pdb_name = (elem + str(i)).ljust(4)[:4]
        line = f"ATOM  {i:>5d} {pdb_name:<4s} UNK     1    {pos.x:>8.3f}{pos.y:>8.3f}{pos.z:>8.3f}  1.00  0.00          {ad4:<2s}\n"
        lines.append(line)
    lines.append("END\n")
    with open(pdbqt_path, "w") as f:
        f.writelines(lines)
    record["pdbqt"] = str(pdbqt_path)
    return True


def main():
    # Load existing ligands
    db_path = DATA_DIR / "ligands_database.json"
    with open(db_path) as f:
        existing = json.load(f)
    existing_names = {r["name"] for r in existing}
    print(f"Existing ligands: {len(existing)}")

    # Load ChEMBL drugs
    chembl_path = DATA_DIR / "chembl_fda_approved.csv"
    chembl_drugs = []
    with open(chembl_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            smi = row.get("smiles", "").strip()
            if not smi:
                continue
            cid = row.get("chembl_id", "").strip()
            name = row.get("name", "").strip() or cid
            # Sanitize name
            safe_name = name.replace("/", "_").replace(" ", "_").replace(",", "_")
            for ch in "()[]{}'\"*":
                safe_name = safe_name.replace(ch, "_")
            if safe_name in existing_names:
                continue
            chembl_drugs.append({
                "chembl_id": cid,
                "name": safe_name,
                "smiles": smi,
                "mw": row.get("mw", ""),
                "alogp": row.get("alogp", ""),
            })

    print(f"ChEMBL drugs: {len(chembl_drugs)} (after dedup)")

    # Check meeko availability
    meeko_ok = False
    try:
        from meeko import MoleculePreparation, PDBQTWriterLegacy
        meeko_ok = True
    except ImportError:
        pass

    # Process each ChEMBL drug
    new_records = []
    meeko_n = 0
    obabel_n = 0
    manual_n = 0
    failed = 0

    for i, drug in enumerate(chembl_drugs):
        name = drug["name"]
        smi = drug["smiles"]

        # Prepare 3D
        rec = prepare_3d_molecule(name, smi, {
            "CHEMBL_ID": drug["chembl_id"],
            "Type": "FDA-approved (ChEMBL)",
        })
        if rec is None:
            failed += 1
            continue
        rec["type"] = "FDA-approved (ChEMBL)"
        rec["known_kd_uM"] = ""

        # Convert to PDBQT
        converted = False
        if meeko_ok and convert_to_pdbqt_meeko(rec):
            meeko_n += 1
            converted = True
        elif convert_to_pdbqt_obabel(rec):
            obabel_n += 1
            converted = True
        elif convert_to_pdbqt_manual(rec):
            manual_n += 1
            converted = True

        if not converted:
            failed += 1
            continue

        new_records.append(rec)

        if (i + 1) % 20 == 0:
            print(f"  [{i+1}/{len(chembl_drugs)}] meeko={meeko_n} obabel={obabel_n} manual={manual_n} fail={failed}")

    print(f"\n=== Conversion Summary ===")
    print(f"  Meeko:  {meeko_n}")
    print(f"  Obabel: {obabel_n}")
    print(f"  Manual: {manual_n}")
    print(f"  Failed: {failed}")
    print(f"  New PDBQT ligands: {len(new_records)}")

    # Merge with existing
    all_records = existing + new_records
    with open(db_path, "w") as f:
        json.dump(all_records, f, indent=2)

    pdbqt_count = len(list(PDBQT_DIR.glob("*.pdbqt")))
    print(f"\nTotal PDBQT ligands: {pdbqt_count}")
    print(f"Total in database: {len(all_records)}")
    print(f"Database saved: {db_path}")


if __name__ == "__main__":
    main()
