#!/usr/bin/env python3
"""
03_run_docking.py
Run AutoDock Vina virtual screening of SMVT (SLC5A6) against:
1. Known interactors (validation set)
2. FDA-approved drug library

Pipeline:
1. Ligand preparation (SDF -> PDBQT)
2. Receptor preparation (PDB -> PDBQT)
3. Define docking grid
4. Run Vina docking
5. Parse and rank results
"""

import os, sys, json, subprocess, math, time, csv
from pathlib import Path

# ============================================================
# Paths
# ============================================================
BASE = Path(r"D:\Researching\SMVT")
DATA_DIR = BASE / "03_Analysis" / "data"
OUTPUTS = BASE / "03_Analysis" / "outputs"
LIGANDS_DIR = DATA_DIR / "ligands"
PDBQT_DIR = DATA_DIR / "pdbqt_ligands"
RESULTS_DIR = DATA_DIR / "docking_results"
SCRIPTS_DIR = BASE / "03_Analysis" / "scripts"

os.makedirs(PDBQT_DIR, exist_ok=True)
os.makedirs(RESULTS_DIR, exist_ok=True)
os.makedirs(OUTPUTS, exist_ok=True)

PYTHON = r"C:\anaconda3\python.exe"
VINA = r"C:\Users\woodh\bin\vina.exe"
VINA_SPLIT = r"C:\Users\woodh\bin\vina_split.exe"
OBABEL = r"C:\anaconda3\Scripts\obabel.exe"

# ============================================================
# Docking configuration
# ============================================================
DOCKING_CONFIG = {
    "center_x": 5.0, "center_y": 1.5, "center_z": -2.4,
    "size_x": 25, "size_y": 25, "size_z": 25,
    "exhaustiveness": 16,
    "num_modes": 9,
    "energy_range": 3,
}
RECEPTOR_PDBQT = str(DATA_DIR / "receptor.pdbqt")

# Try to load refined config if exists
_config_path = DATA_DIR / "docking_config.json"
if _config_path.exists():
    try:
        with open(_config_path) as _f:
            _cfg = json.load(_f)
        DOCKING_CONFIG["center_x"] = _cfg.get("center_x", DOCKING_CONFIG["center_x"])
        DOCKING_CONFIG["center_y"] = _cfg.get("center_y", DOCKING_CONFIG["center_y"])
        DOCKING_CONFIG["center_z"] = _cfg.get("center_z", DOCKING_CONFIG["center_z"])
        DOCKING_CONFIG["size_x"] = _cfg.get("size_x", DOCKING_CONFIG["size_x"])
        DOCKING_CONFIG["size_y"] = _cfg.get("size_y", DOCKING_CONFIG["size_y"])
        DOCKING_CONFIG["size_z"] = _cfg.get("size_z", DOCKING_CONFIG["size_z"])
        print("Loaded docking config from file")
    except:
        pass

# ============================================================
# Functions
# ============================================================

def convert_ligands_with_meeko():
    """Convert all SDF ligands to PDBQT using meeko."""
    from meeko import MoleculePreparation, PDBQTWriterLegacy
    from rdkit import Chem

    ligand_db_path = DATA_DIR / "ligands_database.json"
    if not ligand_db_path.exists():
        print("ERROR: ligands_database.json not found. Run 01_prepare_ligands.py first.")
        return []

    import json
    with open(ligand_db_path) as f:
        ligands = json.load(f)

    print(f"\nConverting {len(ligands)} ligands to PDBQT...")
    success = 0
    for lig in ligands:
        sdf_path = lig["sdf"]
        name = lig["name"]
        pdbqt_path = PDBQT_DIR / f"{name}.pdbqt"

        if pdbqt_path.exists() and os.path.getsize(pdbqt_path) > 100:
            lig["pdbqt"] = str(pdbqt_path)
            success += 1
            continue

        mol = Chem.SDMolSupplier(sdf_path)[0]
        if mol is None:
            print(f"  WARNING: Could not read {sdf_path}")
            continue

        mol.SetProp("_Name", name)

        try:
            preparator = MoleculePreparation()
            mol_setups = preparator.prepare(mol)
            if not mol_setups:
                print(f"  WARNING: meeko prepare failed for {name}")
                continue
            pdbqt_string, is_ok, err_msg = PDBQTWriterLegacy.write_string(mol_setups[0])
            if is_ok:
                with open(pdbqt_path, "w") as f:
                    f.write(pdbqt_string)
                lig["pdbqt"] = str(pdbqt_path)
                success += 1
            else:
                print(f"  WARNING: meeko write failed for {name}: {err_msg}")
        except Exception as e:
            print(f"  ERROR on {name}: {e}")

    print(f"  Converted {success}/{len(ligands)} ligands")
    return ligands


def convert_ligands_with_rdkit(ligands):
    """Fallback: convert SDF to PDBQT using RDKit + manual PDBQT writer."""
    for lig in ligands:
        sdf_path = lig["sdf"]
        name = lig["name"]
        pdbqt_path = PDBQT_DIR / f"{name}.pdbqt"

        if pdbqt_path.exists() and os.path.getsize(pdbqt_path) > 100:
            lig["pdbqt"] = str(pdbqt_path)
            continue

        if not os.path.exists(sdf_path):
            continue

        mol = Chem.SDMolSupplier(sdf_path)[0]
        if mol is None:
            continue

        conf = mol.GetConformer()
        pdbqt_lines = [f"REMARK  GENERATED BY rdkit_pdbqt_writer\n"]
        atom_idx = 0
        for atom in mol.GetAtoms():
            atom_idx += 1
            pos = conf.GetAtomPosition(atom.GetIdx())
            elem = atom.GetSymbol()
            # Basic AD4 type assignment
            if elem == 'C':
                ad4 = 'C'
            elif elem == 'N':
                ad4 = 'N'
            elif elem == 'O':
                ad4 = 'O'
            elif elem == 'S':
                ad4 = 'S'
            elif elem == 'H':
                ad4 = 'H'
            elif elem == 'F':
                ad4 = 'F'
            elif elem == 'Cl':
                ad4 = 'Cl'
            elif elem == 'Br':
                ad4 = 'Br'
            elif elem == 'I':
                ad4 = 'I'
            elif elem == 'P':
                ad4 = 'P'
            else:
                ad4 = elem

            line = f"ATOM  {atom_idx:>5d}  {atom.GetName():<4s} UNK     1    {pos.x:>8.3f}{pos.y:>8.3f}{pos.z:>8.3f}  1.00  0.00          {ad4:<2s}\n"
            pdbqt_lines.append(line)

        pdbqt_lines.append("END\n")

        with open(pdbqt_path, "w") as f:
            f.writelines(pdbqt_lines)

        lig["pdbqt"] = str(pdbqt_path)

    return ligands


def run_vina_docking(ligand_pdbqt, output_prefix, config=None):
    """Run AutoDock Vina for a single ligand."""
    if config is None:
        config = DOCKING_CONFIG

    output_pdbqt = str(RESULTS_DIR / f"{output_prefix}_output.pdbqt")
    log_txt = str(RESULTS_DIR / f"{output_prefix}_log.txt")

    cmd = [
        VINA,
        "--receptor", RECEPTOR_PDBQT,
        "--ligand", ligand_pdbqt,
        "--out", output_pdbqt,
        "--center_x", str(config["center_x"]),
        "--center_y", str(config["center_y"]),
        "--center_z", str(config["center_z"]),
        "--size_x", str(config["size_x"]),
        "--size_y", str(config["size_y"]),
        "--size_z", str(config["size_z"]),
        "--exhaustiveness", str(config["exhaustiveness"]),
        "--num_modes", str(config["num_modes"]),
        "--energy_range", str(config["energy_range"]),
    ]

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
        with open(log_txt, "w") as f:
            f.write(result.stdout)
            if result.stderr:
                f.write("\n--- STDERR ---\n")
                f.write(result.stderr)

        # Parse results
        results = parse_vina_output(result.stdout, output_prefix)
        results["log_file"] = log_txt
        results["output_pdbqt"] = output_pdbqt if os.path.exists(output_pdbqt) else ""

        return results

    except subprocess.TimeoutExpired:
        print(f"  TIMEOUT: {output_prefix}")
        return {"ligand": output_prefix, "error": "timeout", "modes": []}
    except Exception as e:
        print(f"  ERROR: {output_prefix}: {e}")
        return {"ligand": output_prefix, "error": str(e), "modes": []}


def parse_vina_output(vina_stdout, ligand_name):
    """Parse Vina output for binding affinity results."""
    lines = vina_stdout.strip().split("\n")
    results = {"ligand": ligand_name, "modes": []}

    in_table = False
    for line in lines:
        # Vina v1.2.x output format
        if line.startswith("mode |") or line.startswith("-----"):
            in_table = True
            continue
        if in_table and line.strip() == "":
            in_table = False
            continue
        if in_table:
            parts = line.strip().split()
            if len(parts) >= 5:
                try:
                    mode = int(parts[0])
                    affinity = float(parts[1])
                    rmsd_lb = float(parts[2])
                    rmsd_ub = float(parts[3])
                    results["modes"].append({
                        "mode": mode,
                        "affinity_kcal_mol": affinity,
                        "rmsd_lower": rmsd_lb,
                        "rmsd_upper": rmsd_ub,
                    })
                except (ValueError, IndexError):
                    continue

    if results["modes"]:
        results["best_affinity"] = min(m["affinity_kcal_mol"] for m in results["modes"])
    else:
        results["best_affinity"] = 999.0

    return results


def run_batch_docking(ligands, max_workers=4):
    """Run docking for all ligands, optionally in parallel."""
    all_results = []
    known_results = []
    fda_results = []

    for i, lig in enumerate(ligands):
        name = lig["name"]
        pdbqt_path = lig.get("pdbqt", "")

        if not pdbqt_path or not os.path.exists(pdbqt_path):
            print(f"  SKIP {name}: no PDBQT file")
            continue

        print(f"  [{i+1}/{len(ligands)}] Docking {name}...", end=" ", flush=True)
        result = run_vina_docking(pdbqt_path, name)
        result["type"] = lig.get("type", "unknown")
        result["known_kd_uM"] = lig.get("known_kd_uM", "")
        result["mwt"] = lig.get("mwt", "")
        result["logp"] = lig.get("logp", "")

        if result["modes"]:
            print(f"best={result['best_affinity']:.2f} kcal/mol")
        else:
            print("FAILED")

        all_results.append(result)

    return all_results


def analyze_results(all_results):
    """Analyze and rank docking results."""
    known_interactors = [r for r in all_results if r.get("known_kd_uM")]
    fda_drugs = [r for r in all_results if r.get("type") == "FDA-approved"]
    failed = [r for r in all_results if r.get("error") or not r.get("modes")]
    successful = [r for r in all_results if r.get("modes")]

    # Rank by best affinity
    ranked = sorted(successful, key=lambda r: r["best_affinity"])

    # Top hits
    top_hits = [r for r in ranked if r["best_affinity"] < -8.0]

    return {
        "total": len(all_results),
        "successful": len(successful),
        "failed": len(failed),
        "known_interactors": len(known_interactors),
        "fda_drugs": len(fda_drugs),
        "top_hits_count": len(top_hits),
        "ranked": ranked,
        "top_hits": top_hits,
        "known_results": known_interactors,
    }


def save_results_csv(analysis, csv_path):
    """Save ranked docking results to CSV."""
    with open(csv_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["Rank", "Ligand", "Type", "Best_Affinity_kcal_mol",
                         "Num_Modes", "Known_Kd_uM", "MW", "LogP", "Error"])
        for rank, r in enumerate(analysis["ranked"], 1):
            best = r.get("best_affinity", 999)
            modes = r.get("modes", [])
            error = r.get("error", "")
            writer.writerow([
                rank, r["ligand"], r.get("type", ""),
                f"{best:.2f}", len(modes),
                r.get("known_kd_uM", ""), r.get("mwt", ""), r.get("logp", ""),
                error
            ])
    print(f"\nResults saved: {csv_path}")


def main():
    print("=" * 60)
    print("SMVT (SLC5A6) Molecular Docking Virtual Screening")
    print("=" * 60)

    # Step 1: Load ligand database
    ligand_db_path = DATA_DIR / "ligands_database.json"
    if not ligand_db_path.exists():
        print("ERROR: No ligand database found. Run 01_prepare_ligands.py first.")
        sys.exit(1)

    import json, csv
    with open(ligand_db_path) as f:
        ligands = json.load(f)
    print(f"\nLoaded {len(ligands)} ligands")

    # Step 2: Verify receptor PDBQT
    if not os.path.exists(RECEPTOR_PDBQT):
        print("ERROR: Receptor PDBQT not found. Run pdb_to_pdbqt.py first.")
        sys.exit(1)

    # Step 3: Convert ligands to PDBQT
    try:
        from meeko import MoleculePreparation, PDBQTWriterLegacy
        from rdkit import Chem
        print("\n--- Converting ligands to PDBQT (meeko) ---")
        ligands = convert_ligands_with_meeko()
    except ImportError:
        from rdkit import Chem
        print("\n--- Converting ligands to PDBQT (RDKit fallback) ---")
        ligands = convert_ligands_with_rdkit(ligands)

    # Count valid ligands
    valid = [l for l in ligands if l.get("pdbqt") and os.path.exists(l["pdbqt"])]
    print(f"\nValid PDBQT ligands: {len(valid)}/{len(ligands)}")

    # Step 4: Run docking
    print("\n" + "=" * 60)
    print("Running Vina Docking...")
    print("=" * 60)
    all_results = run_batch_docking(valid)

    # Step 5: Analyze results
    print("\n" + "=" * 60)
    print("Analysis")
    print("=" * 60)
    analysis = analyze_results(all_results)

    print(f"\nTotal docked:     {analysis['total']}")
    print(f"Successful:       {analysis['successful']}")
    print(f"Failed:           {analysis['failed']}")
    print(f"Top hits (<-8):   {analysis['top_hits_count']}")
    print(f"Known interactors: {analysis['known_interactors']}")

    if analysis["ranked"]:
        print(f"\nTop 10 ranked hits:")
        for r in analysis["ranked"][:10]:
            kd = f" (Kd={r.get('known_kd_uM','')}uM)" if r.get('known_kd_uM') else ""
            print(f"  {r['ligand']}: {r['best_affinity']:.2f} kcal/mol{kd}")

        if analysis["known_results"]:
            print(f"\nValidation: Known interactor docking scores:")
            for r in sorted(analysis["known_results"], key=lambda x: x.get("best_affinity", 999)):
                kd_str = f" (exp Kd={r.get('known_kd_uM','')}uM)" if r.get('known_kd_uM') else ""
                print(f"  {r['ligand']}: {r['best_affinity']:.2f} kcal/mol{kd}")

    # Step 6: Save results
    csv_path = str(OUTPUTS / "docking_results.csv")
    save_results_csv(analysis, csv_path)

    # Save full results as JSON
    json_path = OUTPUTS / "docking_results.json"
    with open(json_path, "w") as f:
        json.dump(analysis, f, indent=2, default=str)
    print(f"Full results: {json_path}")

    # Generate report
    print("\n--- Generating summary report ---")
    generate_report(analysis, str(OUTPUTS / "docking_report.md"))


def generate_report(analysis, report_path):
    """Generate a markdown docking report."""
    from datetime import datetime

    known = sorted(analysis.get("known_results", []), key=lambda x: x.get("best_affinity", 999))
    top = analysis.get("top_hits", [])
    all_ranked = analysis.get("ranked", [])

    lines = []
    lines.append(f"# SMVT (SLC5A6) Virtual Screening Docking Report")
    lines.append(f"")
    lines.append(f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"**Target:** SMVT / SLC5A6 (Sodium-dependent multivitamin transporter)")
    lines.append(f"**Structure:** AlphaFold2 model (AF-Q9Y289-F1)")
    lines.append(f"**Docking Engine:** AutoDock Vina v1.2.7")
    lines.append(f"**Ligand Library:** {analysis['total']} compounds (known interactors + FDA-approved drugs)")
    lines.append(f"")
    lines.append(f"## Summary")
    lines.append(f"")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total docked | {analysis['total']} |")
    lines.append(f"| Successful | {analysis['successful']} |")
    lines.append(f"| Failed | {analysis['failed']} |")
    lines.append(f"| Known interactors | {analysis['known_interactors']} |")
    lines.append(f"| FDA drugs screened | {analysis['fda_drugs']} |")
    lines.append(f"| Hits (affinity < -8.0 kcal/mol) | {analysis['top_hits_count']} |")
    lines.append(f"")
    lines.append(f"## Docking Configuration")
    lines.append(f"")
    lines.append(f"| Parameter | Value |")
    lines.append(f"|----------|-------|")
    lines.append(f"| Box center | ({DOCKING_CONFIG['center_x']}, {DOCKING_CONFIG['center_y']}, {DOCKING_CONFIG['center_z']}) |")
    lines.append(f"| Box size | {DOCKING_CONFIG['size_x']} x {DOCKING_CONFIG['size_y']} x {DOCKING_CONFIG['size_z']} A |")
    lines.append(f"| Exhaustiveness | {DOCKING_CONFIG['exhaustiveness']} |")
    lines.append(f"| Max modes | {DOCKING_CONFIG['num_modes']} |")
    lines.append(f"")
    lines.append(f"## Validation: Known SMVT Interactors")
    lines.append(f"")
    lines.append(f"| Ligand | Docking Score (kcal/mol) | Experimental Kd (uM) | Type |")
    lines.append(f"|--------|-------------------------|---------------------|------|")
    for r in known:
        kd = r.get('known_kd_uM', '')
        typ = r.get('type', '')
        lines.append(f"| {r['ligand']} | {r.get('best_affinity', 999):.2f} | {kd} | {typ} |")

    missing_known = [r for r in known if not r.get('modes')]
    if missing_known:
        lines.append(f"\n### Failed Known Interactors")
        for r in missing_known:
            lines.append(f"- {r['ligand']}: {r.get('error', 'unknown error')}")

    if top:
        lines.append(f"\n## Top Hits (affinity < -8.0 kcal/mol)")
        lines.append(f"")
        lines.append(f"| Rank | Ligand | Score (kcal/mol) | Modes | Type |")
        lines.append(f"|------|--------|-----------------|-------|------|")
        for rank, r in enumerate(sorted(top, key=lambda x: x['best_affinity']), 1):
            typ = r.get('type', '')
            lines.append(f"| {rank} | {r['ligand']} | {r['best_affinity']:.2f} | {len(r['modes'])} | {typ} |")

    lines.append(f"\n## Top 50 Ranked Compounds")
    lines.append(f"")
    lines.append(f"| Rank | Ligand | Score (kcal/mol) | Modes | Type |")
    lines.append(f"|------|--------|-----------------|-------|------|")
    for rank, r in enumerate(all_ranked[:50], 1):
        typ = r.get('type', '')
        lines.append(f"| {rank} | {r['ligand']} | {r['best_affinity']:.2f} | {len(r['modes'])} | {typ} |")

    lines.append(f"\n## Methods")
    lines.append(f"")
    lines.append(f"1. **Receptor preparation**: AlphaFold2 model (AF-Q9Y289-F1) was prepared with hydrogens")
    lines.append(f"   and converted to PDBQT format with AD4 atom typing.")
    lines.append(f"2. **Ligand preparation**: SMILES strings converted to 3D SDF with RDKit (ETKDGv3),")
    lines.append(f"   then to PDBQT using Meeko.")
    lines.append(f"3. **Docking**: AutoDock Vina v1.2.7 with default scoring function.")
    lines.append(f"   Binding pocket defined at the central cavity of the transmembrane domain.")
    lines.append(f"4. **Analysis**: Compounds ranked by best binding affinity (kcal/mol).")
    lines.append(f"   Threshold for top hits: < -8.0 kcal/mol.")
    lines.append(f"")
    lines.append(f"## References")
    lines.append(f"")
    lines.append(f"1. Prasad PD, et al. (1999) Human placental sodium-dependent multivitamin transporter.")
    lines.append(f"   J Biol Chem.")
    lines.append(f"2. Balamurugan K, et al. (2005) Regulation of SMVT by lipoic acid.")
    lines.append(f"3. Said HM, et al. (2003) NSAID interactions with SMVT. AJP.")
    lines.append(f"4. Eberhardt J, et al. (2021) AutoDock Vina 1.2.0. J Comput Chem.")
    lines.append(f"")

    with open(report_path, "w") as f:
        f.write("\n".join(lines))
    print(f"Report: {report_path}")


if __name__ == "__main__":
    main()
