#!/usr/bin/env python3
"""
PDB to PDBQT converter for AutoDock Vina.
Converts a prepared PDB file to PDBQT format with AD4 atom typing.
Handles standard amino acid residues by assigning AD4 types.
"""

import os, sys

# AD4 atom types for standard amino acid atoms (based on element and hybridization)
# These cover the most common atoms from the AutoDock4 force field
AD4_ELEMENT_MAP = {
    'C': 'C',
    'A': 'C',  # aromatic carbon - but we use 'A' for aromatic
    'N': 'N',
    'O': 'O',
    'H': 'H',
    'S': 'S',
    'P': 'P',
    'F': 'F',
    'Cl': 'Cl',
    'Br': 'Br',
    'I': 'I',
}

# For polar hydrogens that can H-bond, use HD
# For non-polar hydrogens, use H
# For hydrogens on N, O, S: HD (donor)
# For hydrogens on C: H

def get_ad4_type(element, atom_name, resname):
    """Determine AD4 atom type based on element, atom name and residue."""
    element = element.strip().upper()
    atom_name = atom_name.strip().upper()
    resname = resname.strip().upper()

    if element == 'C':
        # Check if it's aromatic carbon
        if atom_name in ('CA', 'CB', 'CD', 'CE', 'CG', 'CH', 'CZ', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6') and resname in ('PHE', 'TYR', 'TRP', 'HIS', 'HIP', 'HID', 'HIE'):
            return 'A'  # aromatic carbon
        return 'C'

    elif element == 'N':
        return 'N'

    elif element == 'O':
        return 'O'

    elif element == 'S':
        return 'S'

    elif element == 'H':
        # Check if it's a polar hydrogen (on N, O, S)
        # We can check by the atom name
        atom_name_stripped = atom_name.replace('H', '').replace('D', '')
        if atom_name.startswith('H'):
            hydrogens_on = atom_name[1:]  # e.g., 'HG', 'HD', 'HE', 'HH', 'HZ'
            if not hydrogens_on:
                return 'H'
            if hydrogens_on in ('G', 'D', 'E', 'Z', 'G1', 'G2', 'D1', 'D2', 'D3', 'E1', 'E2', 'E3', 'Z1', 'Z2', 'Z3'):
                # Could be on N/O/S or C, hard to tell from PDB alone
                # Conservative: assume non-polar unless known
                return 'H'
        return 'H'

    elif element == 'F':
        return 'F'
    elif element == 'CL':
        return 'Cl'
    elif element == 'BR':
        return 'Br'
    elif element == 'I':
        return 'I'
    elif element == 'P':
        return 'P'

    return element  # fallback


def convert_pdb_to_pdbqt(pdb_path, pdbqt_path):
    """Convert a PDB file to PDBQT format."""
    with open(pdb_path) as f:
        lines = f.readlines()

    output_lines = []
    atom_count = 0

    # Add PDBQT header
    output_lines.append("REMARK  GENERATED BY pdb_to_pdbqt.py\n")
    output_lines.append("REMARK  AutoDock Vina PDBQT format\n")

    for line in lines:
        if line.startswith("ATOM") or line.startswith("HETATM"):
            if len(line) < 66:
                continue

            # Parse PDB ATOM line
            record = line[0:6].strip()
            serial = line[6:11].strip()
            atom_name = line[12:16].strip()
            alt_loc = line[16:17].strip()
            resname = line[17:20].strip()
            chain = line[21:22].strip()
            resnum = line[22:26].strip()
            x = line[30:38].strip()
            y = line[38:46].strip()
            z = line[46:54].strip()
            occ = line[54:60].strip() or "1.00"
            bfactor = line[60:66].strip() or "0.00"
            element = line[76:78].strip() or atom_name[0]

            if alt_loc and alt_loc != 'A':
                continue  # Skip alternate conformations except 'A'

            # Get AD4 type
            ad4_type = get_ad4_type(element, atom_name, resname)

            atom_count += 1
            new_serial = str(atom_count)

            # PDBQT format with exact PDB column positions
            # Col 1-6: ATOM  , Col 7-11: serial, Col 12: blank, Col 13-16: atom name
            # Col 17: alt_loc, Col 18-20: resname, Col 21: blank, Col 22: chain
            # Col 23-26: resnum, Col 27-30: blank, Col 31-38: x, Col 39-46: y, Col 47-54: z
            # Col 55-60: occ, Col 61-66: bfactor, Col 77-78: AD4 type
            out_line = f"ATOM  {new_serial:>5s} {atom_name:<4s} {resname:<3s} {chain}{resnum:>4s}    {x:>8s}{y:>8s}{z:>8s}{occ:>6s}{bfactor:>6s}          {ad4_type:<2s}\n"
            output_lines.append(out_line)

        elif line.startswith("TER"):
            output_lines.append(line)
        elif line.startswith("END"):
            break

    output_lines.append("END\n")

    with open(pdbqt_path, "w") as f:
        f.writelines(output_lines)

    return atom_count


def main():
    pdb_path = r"D:\Researching\SMVT\02_Data\cleaned\AF-Q9Y289-F1_prepared.pdb"
    pdbqt_path = r"D:\Researching\SMVT\03_Analysis\data\receptor.pdbqt"

    os.makedirs(os.path.dirname(pdbqt_path), exist_ok=True)

    print(f"Converting PDB to PDBQT...")
    print(f"  Input:  {pdb_path}")
    print(f"  Output: {pdbqt_path}")

    atoms = convert_pdb_to_pdbqt(pdb_path, pdbqt_path)
    file_size = os.path.getsize(pdbqt_path)
    print(f"  Atoms written: {atoms}")
    print(f"  File size: {file_size:,} bytes")

    # Verify vina can read it
    vina = r"C:\Users\woodh\bin\vina.exe"
    import subprocess
    result = subprocess.run([vina, "--receptor", pdbqt_path, "--help"],
                          capture_output=True, text=True, timeout=10)
    if "Error" in result.stderr:
        print(f"  WARNING: {result.stderr[:200]}")
    else:
        print(f"  Vina accepted the PDBQT file")

    print("Done!")


if __name__ == "__main__":
    main()
